#!/bin/bash

### sm - transmogrify $2.sm to $2.py where $2.sm is a simple state machine description ###

set -e
export SHELLOPTS

# set up env vars depending on whether this script was called from elsewhere or is the top level
if [ "$#" -eq 0 ]; then
    # no arguments - top level build
    # current working directory
    export PBPWD=$(pwd)
    export PBP=~/projects/pbp-dev
    export PYTHONPATH="${PBP}/kernel:${PYTHONPATH}"
    export PBPCALLER=$PBPWD
    fname="looptest"
    ${PBP}/resetlog

elif [ "$#" -eq 3 ]; then
    # exactly three arguments
    # $1 is callee's working dir
    # $2 is basename of the caller's file to be processed
    # $3 is caller's working dir
    # push a new value of PBPWD onto the stack, which will get unwound to its previous value when this script ends
    export PBPWD=$1
    fname="$2"
    export PBPCALLER="$3"
else
    # error: usage
    echo "Usage: $0 [diagram callerWDIR]" >&2
    exit 1
fi

rm -f out.*
rm -f *.json
cd "${PBPWD}"

######### commands specific to this project #############


${PBP}/t2t smdiagram1 <looptest.drawio

# ${PBP}/t2t sm sm-metapy <"${fname}.sm" |\
#     ${PBP}/brace_indent |\
#     ${PBP}/del_blank_lines |\
#     ${PBP}/rigid_indent '            ' \
#     >out.py

############################



## move results to caller's working directory, if no errors
if [ -f out.✗ ]
then
    echo
    echo ">> ERROR <<"
    cat out.✗
else
    mv out.py "${PBPCALLER}/${fname}.py"
fi

