#!/bin/bash

######### commands specific to this project #############

target=looptest
vsh=smdpl

${PBP}/das2json ${vsh}.drawio
export PBPSTEPPING="1"
python smdpl.py ${target}.drawio main ${vsh}.drawio.json | ${PBP}/splitoutputs
cat out.py | python replace.py "✣" "${target}" >"${target}.py"

############################



