#!/bin/bash

### sm - transmogrify $2.sm to $2.py where $2.sm is a simple state machine description ###

set -e
export SHELLOPTS

# set up env vars depending on whether this script was called from elsewhere or is the top level
if [ "$#" -eq 0 ]; then
    # no arguments - top level build
    # current working directory
    export PBPWD=$(pwd)
    export PBP=~/projects/pbp-dev
    export PYTHONPATH="${PBP}/kernel:${PYTHONPATH}"
    export PBPCALLER=$PBPWD
    fname="looptest"
    ${PBP}/resetlog

elif [ "$#" -eq 3 ]; then
    # exactly three arguments
    # $1 is callee's working dir
    # $2 is basename of the caller's file to be processed
    # $3 is caller's working dir
    # push a new value of PBPWD onto the stack, which will get unwound to its previous value when this script ends
    export PBPWD=$1
    fname="$2"
    export PBPCALLER="$3"
else
    # error: usage
    echo "Usage: $0 [diagram callerWDIR]" >&2
    exit 1
fi

rm -f out.*
rm -f *.json
cd "${PBPWD}"

######### commands specific to this project #############

echo 1
${PBP}/t2t rmgeometry <looptest.drawio >1.mr
echo 2
${PBP}/t2t cull <1.mr >2.mr
echo 3
${PBP}/t2t rmdiv <2.mr >3.mr
echo 4
${PBP}/t2t rmspan <3.mr >4.mr
echo 5
${PBP}/t2t unhtml <4.mr >5.mr
echo 6
${PBP}/t2t kinds <5.mr >6.mr
echo 7
${PBP}/t2t mr2json <6.mr >7.json
echo 7a
${PBP}/t2t mr2pl <6.mr | python commarpar.py >7.pl

    

# ${PBP}/t2t sm sm-metapy <"${fname}.sm" |\
#     ${PBP}/brace_indent |\
#     ${PBP}/del_blank_lines |\
#     ${PBP}/rigid_indent '            ' \
#     >out.py

############################



## move results to caller's working directory, if no errors
if [ -f out.✗ ]
then
    echo
    echo ">> ERROR <<"
    cat out.✗
else
    mv out.py "${PBPCALLER}/${fname}.py"
fi

