#!/bin/bash

# Quit immediately if there are any errors
set -e

# Variable assignments (uppercase = exported, lowercase = local)
export PBP_WD="$(pwd)"
export PBP_LIBD="$(python -c "import os, sys; print(os.path.abspath(sys.argv[1]))" "$2")"

# Get full path of first parameter, then extract directory and basename
param1_full="$(python -c "import os, sys; print(os.path.abspath(sys.argv[1]))" "$1")"
export PBP_APPD="$(dirname "${param1_full}")"
app_main_base="$(basename "${param1_full}" .drawio)"
app_main="${PBP_APPD}/${app_main_base}.drawio"

# PBP arg: third parameter as full path if it's a file, otherwise just the parameter
if [[ -f "$3" ]]; then
    export PBP_arg="$(python -c "import os, sys; print(os.path.abspath(sys.argv[1]))" "$3")"
else
    export PBP_arg="$3"
fi

source pbp_vars.bash ${PBP_LIBD}

export PBP_WSUPPORT="${PBP_APPD}/support.mjs"

# Push kernel onto PYTHONPATH
export PYTHONPATH="${PBP_LIBD}/kernel-d:${PYTHONPATH}"


# for i in PBP_WD PBP_WSUPPORT PBP_LIBD PBP_APPD app_main PBP_arg PBP_runpbp PBP_indent PBP_t2t PBP_das2json PBP_split_outputs PBP_check_for_errors
# do
#     echo $i "=" ${!i}
# done

# Change to the app directory
cd "${PBP_APPD}"

# Remove all 'out.*' files
rm -f out.*

# Run das2json on app main
"${PBP_das2json}" "${app_main}"

# Run check for errors on app main.json
"${PBP_check_for_errors}" "${app_main}.json"

# Run python and pipe to split outputs
echo runpbp "$PYTHONPATH"
python main.py "${PBP_LIBD}" "${PBP_arg}" main "${app_main}.json" >temp.out
cat temp.out | "${PBP_split_outputs}"

# Check if the run produced "out.✗"
if [[ -f "out.✗" ]]; then
    echo
    mv "out.✗" "ERRORS"
    cat "ERRORS"
    # echo
    # echo
    # echo "!!! ERRORS !!!"
    echo
    exit 1
else
    # Get basename of PBP_arg for output filenames
    arg_basename="$(basename "${PBP_arg}")"

    # Move output files to original working directory with renamed filenames
    mv "out.frish" "${PBP_WD}/${arg_basename}.frish"
    mv "out.dt" "${PBP_WD}/${arg_basename}.dt"
    mv "out.js" "${PBP_WD}/${arg_basename}.js"
    mv "out.py" "${PBP_WD}/${arg_basename}.py"
fi
