#!/bin/bash
${PBP}/pbplog "in pbp/t2t /$@/ T2TVERBOSE=${T2TVERBOSE}"
set -e
RID=${RANDOM}
src=temp.${RID}.src
cat - >${src}

if [ "$#" -eq 1 ]; then
  grammar="${PBPWD}/$1.ohm"
  rewrite="${PBPWD}/$1.rwr"
elif [ "$#" -eq 2 ]; then
  grammar="${PBPWD}/$1.ohm"
  rewrite="${PBPWD}/$2.rwr"
else
  echo "Usage: $0 base            # uses base.ohm and base.rwr" >&2
  echo "   or: $0 grammar-base rewrite-base" >&2
  exit 1
fi

# t2tlibd is the lib directory for t2t
t2tlibd="${PBP}/t2td/lib"
# wsupport is support.js in the current working directory
wsupport="${PBPWD}/support.mjs"


node "${t2tlibd}/rwr.mjs" "${rewrite}" >"${PBPWD}/temp.${RID}.rewrite.mjs"

sed -e 's/`/` + "`" + String.raw`/g' <"${grammar}" >"${PBPWD}/temp.${RID}.grammar"

nanodsl="${PBPWD}/temp.nanodsl.${RID}.mjs"

cat "${t2tlibd}/front.part.js" "${PBPWD}/temp.${RID}.grammar" "${t2tlibd}/middle.part.js" "${t2tlibd}/args.part.js" "${wsupport}" "${PBPWD}/temp.${RID}.rewrite.mjs" "${t2tlibd}/tail.part.js" >"${nanodsl}"

node "${nanodsl}" "${src}"
